# Config file for automatic testing at travis-ci.org
dist: bionic
language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

before_install:
    - PROTOBUF_VERSION=3.13.0
    - PROTOC_FILENAME=protoc-${PROTOBUF_VERSION}-linux-x86_64.zip
    - wget https://github.com/google/protobuf/releases/download/v${PROTOBUF_VERSION}/${PROTOC_FILENAME}
    - unzip $PROTOC_FILENAME -d $HOME/.local
    # We have to install protoc, and python libs for both python and python3, since mypy runs py3
    - sudo apt-get install -qq python3-pip python3-setuptools
    - python -m pip install virtualenv
    - python3 -m pip install virtualenv
script:
    - ./run_test.sh


jobs:
    include:
        - python: 3.8
          before_install: python3 -m pip install black
          script: black --check python/ test/
